# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mcwidget.ui'
#
# Created: Wed Jan 16 12:41:37 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_McWidget(object):
    def setupUi(self, McWidget):
        McWidget.setObjectName(_fromUtf8("McWidget"))
        McWidget.resize(627, 420)
        McWidget.setWindowTitle(QtGui.QApplication.translate("McWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout = QtGui.QHBoxLayout(McWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scrollArea = QtGui.QScrollArea(McWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 607, 400))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setText(QtGui.QApplication.translate("McWidget", "Fluid Levels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.widget_2 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_12.setContentsMargins(-1, 15, -1, 15)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_3 = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("McWidget", "Ch 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_12.addWidget(self.label_3)
        self.multiChannelProgressBar_6 = QtGui.QProgressBar(self.widget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.multiChannelProgressBar_6.setFont(font)
        self.multiChannelProgressBar_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.multiChannelProgressBar_6.setProperty("value", 0)
        self.multiChannelProgressBar_6.setTextVisible(True)
        self.multiChannelProgressBar_6.setOrientation(QtCore.Qt.Horizontal)
        self.multiChannelProgressBar_6.setInvertedAppearance(False)
        self.multiChannelProgressBar_6.setFormat(QtGui.QApplication.translate("McWidget", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelProgressBar_6.setObjectName(_fromUtf8("multiChannelProgressBar_6"))
        self.horizontalLayout_12.addWidget(self.multiChannelProgressBar_6)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.widget_4 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_13.setContentsMargins(-1, 15, -1, 15)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_7 = QtGui.QLabel(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(50, 0))
        self.label_7.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setText(QtGui.QApplication.translate("McWidget", "Ch 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_13.addWidget(self.label_7)
        self.multiChannelProgressBar_7 = QtGui.QProgressBar(self.widget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.multiChannelProgressBar_7.setFont(font)
        self.multiChannelProgressBar_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.multiChannelProgressBar_7.setProperty("value", 0)
        self.multiChannelProgressBar_7.setFormat(QtGui.QApplication.translate("McWidget", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelProgressBar_7.setObjectName(_fromUtf8("multiChannelProgressBar_7"))
        self.horizontalLayout_13.addWidget(self.multiChannelProgressBar_7)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.line_7 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_3.addWidget(self.line_7)
        self.widget_10 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_14.setContentsMargins(-1, 15, -1, 15)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_10 = QtGui.QLabel(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(50, 0))
        self.label_10.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setText(QtGui.QApplication.translate("McWidget", "Ch 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_14.addWidget(self.label_10)
        self.multiChannelProgressBar_8 = QtGui.QProgressBar(self.widget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.multiChannelProgressBar_8.setFont(font)
        self.multiChannelProgressBar_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.multiChannelProgressBar_8.setProperty("value", 0)
        self.multiChannelProgressBar_8.setFormat(QtGui.QApplication.translate("McWidget", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelProgressBar_8.setObjectName(_fromUtf8("multiChannelProgressBar_8"))
        self.horizontalLayout_14.addWidget(self.multiChannelProgressBar_8)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.widget_10)
        self.line_8 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_3.addWidget(self.line_8)
        self.widget_11 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.widget_11)
        self.horizontalLayout_15.setContentsMargins(-1, 15, -1, 15)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_11 = QtGui.QLabel(self.widget_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(50, 0))
        self.label_11.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setText(QtGui.QApplication.translate("McWidget", "Ch 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_15.addWidget(self.label_11)
        self.multiChannelProgressBar_9 = QtGui.QProgressBar(self.widget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.multiChannelProgressBar_9.setFont(font)
        self.multiChannelProgressBar_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.multiChannelProgressBar_9.setProperty("value", 0)
        self.multiChannelProgressBar_9.setFormat(QtGui.QApplication.translate("McWidget", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelProgressBar_9.setObjectName(_fromUtf8("multiChannelProgressBar_9"))
        self.horizontalLayout_15.addWidget(self.multiChannelProgressBar_9)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.widget_11)
        self.line_9 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_3.addWidget(self.line_9)
        self.widget_12 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_12.setObjectName(_fromUtf8("widget_12"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.widget_12)
        self.horizontalLayout_16.setContentsMargins(-1, 15, -1, 15)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_12 = QtGui.QLabel(self.widget_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(50, 0))
        self.label_12.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setText(QtGui.QApplication.translate("McWidget", "Ch 5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_16.addWidget(self.label_12)
        self.multiChannelProgressBar_10 = QtGui.QProgressBar(self.widget_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.multiChannelProgressBar_10.setFont(font)
        self.multiChannelProgressBar_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.multiChannelProgressBar_10.setProperty("value", 0)
        self.multiChannelProgressBar_10.setFormat(QtGui.QApplication.translate("McWidget", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelProgressBar_10.setObjectName(_fromUtf8("multiChannelProgressBar_10"))
        self.horizontalLayout_16.addWidget(self.multiChannelProgressBar_10)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.widget_12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(McWidget)
        QtCore.QMetaObject.connectSlotsByName(McWidget)

    def retranslateUi(self, McWidget):
        pass

